name: Docker Image CI

on:
  pull_request:
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dev:latest .
        # Add path to Dockerfile if it's not in the root directory, e.g., ./path/to/Dockerfile
      
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dev:latest
