name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Server Dependencies
      working-directory: ./server
      run: npm ci

    - name: Install Client Dependencies
      working-directory: ./client
      run: npm ci

    - name: Build Client
      working-directory: ./client
      run: npm run build

    - name: Start Server
      working-directory: ./server
      run: pm2 server --name veeraserver


    # - name: adding env file
    #   run: |
    #   touch .env
    #   echo "${{secrets.PROD_ENV_FILE}}" > .env
    # - run: pm2 restart atsapp


# name: Node.js CI

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
 
